# Generated by Django 5.2.4 on 2025-07-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_verified_user_verified_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcription',
            new_name='Subscription',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='authenticat_user_id_592d39_idx',
            old_name='authenticat_user_id_c6d222_idx',
        ),
    ]
