# Generated by Django 5.2.4 on 2025-07-23 15:59

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_subcription_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_model', models.CharField(blank=True, max_length=225, null=True)),
                ('device_os', models.CharField(blank=True, max_length=225, null=True)),
                ('device_imei', models.CharField(blank=True, max_length=225, null=True)),
                ('device_network', models.CharField(blank=True, max_length=225, null=True)),
                ('device_battery', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('idle', 'Idle')], max_length=225, null=True)),
                ('plan_end', models.DateField(default=datetime.date.today)),
                ('plan_type', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=225, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('licence_key', models.CharField(blank=True, max_length=225, null=True)),
                ('payload_version', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['user', 'id'], name='authenticat_user_id_d44b49_idx'),
        ),
    ]
