# Generated by Django 5.2.4 on 2025-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_target_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='device_unique_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
