# Generated by Django 5.2.4 on 2025-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_target_device_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='name_alias',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
