# Generated by Django 5.2.4 on 2025-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_target_name_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='licence_key',
            new_name='license_key',
        ),
    ]
