# Generated by Django 5.2.4 on 2025-07-24 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_licence_key_target_license_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('message_type', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.target')),
            ],
            options={
                'indexes': [models.Index(fields=['id', 'address'], name='authenticat_id_1ca385_idx')],
            },
        ),
    ]
