# Generated by Django 5.2.4 on 2025-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_smsmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessages',
            name='message_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
