# Generated by Django 5.2.4 on 2025-07-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_smsmessages_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsmessages',
            unique_together={('target', 'message_id')},
        ),
    ]
