# Generated by Django 5.2.4 on 2025-07-25 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_smsmessages_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('phones', models.JSONField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('organization', models.CharField(blank=True, max_length=225, null=True)),
                ('addresses', models.JSONField(blank=True, null=True)),
                ('organizations', models.JSONField(blank=True, null=True)),
                ('websites', models.JSONField(blank=True, null=True)),
                ('socialMedias', models.JSONField(blank=True, null=True)),
                ('groups', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('is_google', models.BooleanField(default=False)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id', 'contact_id'], name='authenticat_id_4986ee_idx')],
                'unique_together': {('contact_id', 'is_google', 'is_whatsapp')},
            },
        ),
    ]
