# Generated by Django 5.2.4 on 2025-07-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='socialMedias',
            new_name='social_medias',
        ),
    ]
