# Generated by Django 5.2.4 on 2025-07-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_socialmedias_contacts_social_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='organization',
        ),
    ]
