# Generated by Django 5.2.4 on 2025-07-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_calllogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogs',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.target'),
            preserve_default=False,
        ),
    ]
